from __future__ import annotations

from pathlib import Path

from docx import Document


ROOT = Path(__file__).resolve().parents[2]
DOCX_PATH = (
    ROOT
    / "docs"
    / "project_blueprints"
    / "V5_5_SLIDE2_SOURCE_UPDATE_North_Slope_Gas_Hydrate_ML_Workflow_Companion_2026-06-17.docx"
)


def _has_paragraph(document: Document, text: str) -> bool:
    return any(paragraph.text.strip() == text for paragraph in document.paragraphs)


def _add_table(document: Document, headers: list[str], rows: list[tuple[str, ...]]) -> None:
    table = document.add_table(rows=1, cols=len(headers))
    table.style = "Table Grid"
    for index, header in enumerate(headers):
        run = table.rows[0].cells[index].paragraphs[0].add_run(header)
        run.bold = True
    for row_values in rows:
        cells = table.add_row().cells
        for index, value in enumerate(row_values):
            cells[index].text = value


def append_science_support_notes(document: Document) -> bool:
    marker = "Science Support Notes For Revised Slides"
    if _has_paragraph(document, marker):
        return False

    document.add_page_break()
    document.add_heading(marker, level=1)
    document.add_paragraph(
        "These notes are the Word/end-material layer behind the revised slides. The slides should keep only short "
        "high-level phrases, while this companion holds the source logic, caveats, and manuscript-ready wording. "
        "Nothing in this section is a project result, occurrence proof, saturation estimate, producibility claim, "
        "or trained-model performance statement."
    )

    document.add_heading("Hydrate Structures, Gas Composition, And The Methane Baseline", level=2)
    document.add_paragraph(
        "Gas hydrate is a clathrate solid: water molecules form cages that physically trap guest gas molecules. "
        "Structure I is the baseline for methane-dominant hydrate and is the structure assumed by the current "
        "methane 5 ppt stability screen. Structure II can be stabilized by larger gas molecules and mixed natural "
        "gas components such as propane or isobutane. Structure H requires a larger hydrocarbon guest plus small "
        "helper gas such as methane. The slide deck can show Structure I, II, and H visually, but it should circle "
        "or otherwise emphasize Structure I because the current equations and stability products are methane "
        "baseline products unless a mentor-approved gas-composition sensitivity case is explicitly invoked."
    )
    document.add_paragraph(
        "Gas composition shifts the pressure-temperature stability boundary. A methane-only or methane-dominant "
        "phase curve is not the same as a mixed-gas phase curve. The current public workflow should therefore say "
        "methane baseline, not final gas chemistry, until gas composition data and scenario policy are approved."
    )

    document.add_heading("Biogenic Versus Thermogenic Gas", level=2)
    document.add_paragraph(
        "Biogenic methane is generated by microbial processes at relatively low temperatures, while thermogenic gas "
        "is generated by thermal maturation of organic matter at depth and commonly brings more C2+ hydrocarbon "
        "components into the discussion. For North Slope hydrate communication, this distinction matters because "
        "microbial methane supports a methane/Structure I baseline, while thermogenic or mixed gas introduces "
        "composition sensitivity and can move the phase boundary. The Word text should state that mixed microbial "
        "and thermogenic gas has been discussed in North Slope/Eileen Trend source literature, but the current "
        "project does not yet have approved gas-composition rows tied to the three-workbook runtime package."
    )

    document.add_heading("Why Gas Hydrates Matter As An Energy Resource", level=2)
    document.add_paragraph(
        "The project should use government resource estimates as regional motivation, not as a result of this "
        "workflow. The current project source ledger points to USGS Fact Sheet 2019-3037, which reports a 2018 "
        "USGS mean estimate of about 54 trillion cubic feet of undiscovered, technically recoverable gas resources "
        "within North Slope gas hydrates. Older project or background material may also mention the 2008 Department "
        "of the Interior/USGS release reporting 85.4 trillion cubic feet for an earlier assessment. If both numbers "
        "appear, keep the year and assessment basis next to the number so the deck does not look inconsistent."
    )
    document.add_paragraph(
        "A regional government resource estimate explains why North Slope hydrates are worth studying. It does not "
        "prove occurrence in any project interval, validate producibility, or replace well-log, core, NMR, "
        "pressure-temperature, and validation evidence."
    )

    document.add_heading("Reservoir Quality And Clean Sandstone", level=2)
    document.add_paragraph(
        "The project is framed around pore-filling hydrate in sand-rich permafrost-associated reservoirs. Clean, "
        "porous sandstone matters because pore-filling hydrate requires pore volume, connected reservoir quality, "
        "and a geologic setting that can charge and preserve hydrate. Low gamma ray can be a clean-sand or lower "
        "shale proxy, but it is only a reservoir-quality gate. High gamma ray, clay-rich zones, thin laminations, "
        "or poor sorting can reduce reservoir quality and can also distort resistivity, NMR, density, and sonic "
        "interpretation. Reservoir quality is a condition that makes hydrate interpretation more plausible, not a "
        "hydrate label by itself."
    )

    document.add_heading("Well, Lithology, And Core Evidence Status", level=2)
    document.add_paragraph(
        "The current runtime story should say that the approved-runtime prototype is organized around three curated "
        "workbooks or datasheets and a working four-well or four-case scope from the latest project direction. "
        "However, the public-safe header-only verification on this machine confirms only two named well aliases: "
        "MTE as Mount Elbert / Well-MTE and IGS as Ignik Sikumi / Well-IGS. It also finds MTE_refined and "
        "IGS_refined as refined or alignment sheet views, not verified additional distinct wells. MLK and ETG are "
        "not verified in committed public-safe metadata."
    )
    document.add_paragraph(
        "For source support, Mount Elbert is supported by public source literature as a cored and logged North Slope "
        "gas hydrate stratigraphic test well with NMR, P- and S-wave velocity, resistivity, and core/reservoir "
        "context. Ignik Sikumi is supported as an Eileen Trend case-study/production-test context in North Slope "
        "source literature. Hydrate-01 and newer HYDRATE 02 sources support the broader ANS log/core/NMR/reservoir "
        "logic, but they should not be silently treated as the same rows or labels as the current three-workbook "
        "runtime package. The missing item is a clean approved-runtime metadata export confirming exact workbook, "
        "sheet, well, location, lithology/core, NMR, pressure-core, and target-label provenance."
    )

    document.add_heading("Complementary Evidence, Not One-Curve Proof", level=2)
    _add_table(
        document,
        ["Evidence family", "What it contributes", "Common mimic or limitation", "Word/slide role"],
        [
            ("GR / lithology", "Clean-sand and reservoir-quality gate.", "Clean non-hydrate sand, radioactive minerals, shale laminations, and depth mismatch.", "Input/context, never hydrate proof."),
            ("Resistivity", "Hydrate-compatible resistive pore fill when reservoir and water-salinity context fit.", "Free gas, ice, cement, tight rock, invasion, salinity, and shale effects.", "Strong feature only when paired with other evidence."),
            ("Density / porosity / NMR", "Pore volume, mobile-water response, NMR-density separation, and calibration support.", "Clay-bound water, depth mismatch, tool processing, missing NMR, or target leakage.", "Measured inputs or target/calibration depending on header role."),
            ("Vp, Vs, Vp/Vs, impedance", "Frame stiffness, velocity response, and elastic contrasts.", "Compaction, cement, carbonate, ice, gas, stress, and unit-conversion errors.", "Measured or derived features with provenance flags."),
            ("Core / pressure core", "Lithology, porosity, permeability, pressure-core quality, and calibration evidence.", "Sparse intervals, depth offsets, sampling bias, and disturbed samples.", "Calibration/validation, not an automatic continuous label."),
            ("Caliper / washout QC", "Whether log responses are trustworthy in the borehole.", "Missing caliper, bit-size uncertainty, or bad-hole intervals.", "QC only; not hydrate evidence."),
            ("P-T stability", "Whether hydrate is admissible under a stated phase-curve and temperature model.", "Gas chemistry, salinity, geothermal uncertainty, missing temperature profile.", "Context/screen/caveat only."),
        ],
    )

    document.add_heading("Equations As Screening Transformations", level=2)
    document.add_paragraph(
        "The equations in the slide and Word logic are physics and screening transformations. They convert measured "
        "or approved-context quantities into interpretable features or admissibility checks. Examples include "
        "hydrostatic pressure from depth, temperature-gradient or profile-based temperature, methane 5 ppt phase "
        "boundary lookup, density porosity, Archie-style water/hydrate saturation reference logic, sonic slowness "
        "to Vp/Vs, acoustic impedance, and elastic attributes such as mu-rho and lambda-rho. These transformations "
        "can support feature engineering and review, but they cannot prove hydrate without aligned labels, lithology, "
        "core/NMR support, QC, and validation."
    )
    document.add_paragraph(
        "If a saturation-like equation or field creates Sgh, S_h, Sh, NMR_SAT, Hydrate Saturation, Swr, S_wr, an "
        "occurrence label, or an interpreted phase label, it belongs on the Y-only/calibration side. It can supervise "
        "or validate a model after mentor approval; it must not enter X_allowed as an ordinary predictor."
    )

    document.add_heading("Current ML Scope: Three Workbooks And Four Working Cases", level=2)
    document.add_paragraph(
        "The ML draft should describe the three curated workbook/datasheet package as a controlled approved-runtime "
        "prototype. Its purpose is to preserve original headers, discover schema families, enforce target leakage "
        "rules, test train-only 0-1 scaling, and exercise occurrence-classification and saturation-regression code "
        "paths without exposing approved rows. Saturation targets should be treated as fractions on a 0-1 scale, with "
        "sheet-level runtime verification still required. Depth remains the alignment axis unless mentor approval "
        "changes that policy."
    )
    document.add_paragraph(
        "The public wording should say that the current project direction is a four-well/four-case ML scope from "
        "three workbooks, but that public-safe metadata has not yet verified four distinct actual wells. Final "
        "model training, occurrence classes, saturation regression claims, and performance metrics wait for the "
        "approved workbook metadata, target authority, lithology/core support, and whole-well or grouped validation "
        "split."
    )

    document.add_heading("Detailed Source Anchors For Word / End Material", level=1)
    document.add_paragraph(
        "Use these as manuscript or companion citations. Do not cite internal source maps, screenshot filenames, "
        "prompts, or artifact indexes as scientific sources."
    )
    _add_table(
        document,
        ["Source", "Supports", "Use in Word companion", "Guardrail"],
        [
            ("USGS Modern Perspective on Gas Hydrates, https://www.usgs.gov/news/featured-story/modern-perspective-gas-hydrates", "Basic gas hydrate definition, permafrost and marine settings, public-domain context.", "Short definition and why hydrates are investigated as an energy/resource topic.", "Background only; not North Slope interval proof."),
            ("Sloan and Koh, Clathrate Hydrates of Natural Gases, 3rd ed.; World Atlas structure figure used in Slide 2", "Structure I, Structure II, Structure H, guest-size and gas-composition logic.", "Explain why methane/Structure I is the current baseline and mixed-gas cases are sensitivity scenarios.", "Check figure rights/captions before public release."),
            ("USGS OF 96-272 biogenic vs thermogenic discussion, https://pubs.usgs.gov/of/1996/of96-272/ch03s07.html", "Thermogenic/mixed gases can include ethane/propane and shift stability relative to methane.", "Explain why gas source and composition matter for phase-boundary policy.", "Do not infer workbook gas composition without approved rows."),
            ("Collett et al. 2019, USGS Fact Sheet 2019-3037, https://doi.org/10.3133/fs20193037", "2018 North Slope gas hydrate assessment; about 54 Tcf mean undiscovered technically recoverable gas.", "Current regional motivation/resource estimate.", "Regional estimate only, not project validation or producibility proof."),
            ("DOI/USGS 2008 North Slope gas hydrate assessment release, https://www.doi.gov/sites/default/files/archive/news/archive/08_News_Releases/111208.html", "Older estimate of 85.4 Tcf technically recoverable gas from North Slope hydrates.", "Historical comparison only if older slides or notes mention 85.4 Tcf.", "Keep date/assessment basis attached; do not mix with 2018 estimate."),
            ("Collett, Boswell, and Zyrianova 2022, Alaska North Slope terrestrial gas hydrate systems, https://doi.org/10.1007/978-3-030-81186-0_16", "Mount Elbert, Ignik Sikumi, Hydrate-01, scientific-drilling context, and regional resource framing.", "Connect four-case runtime discussion to known ANS case-study wells without overclaiming workbook mapping.", "Source context; not proof that current workbooks contain every cited well."),
            ("Lee and Collett 2011, Mount Elbert in-situ saturation from well logs, https://doi.org/10.1016/j.marpetgeo.2009.06.007", "NMR, P- and S-wave velocity, resistivity, core/reservoir data, and saturation-method comparison.", "Support complementary evidence and MTE/Mount Elbert source context.", "Do not copy source saturation values as project outputs."),
            ("Haines et al. 2022, Hydrate-01 well-log saturation and reservoir characteristics, https://doi.org/10.1021/acs.energyfuels.1c04100", "Sonic, resistivity, NMR comparison; reservoir quality, shale fraction, permeability, and Vp/Vs discussion.", "Support why reservoir quality and multiple log families are needed.", "Hydrate-01 context is not automatically the current three-workbook data."),
            ("Zyrianova, Collett, and Boswell 2024, Eileen Gas Hydrate Trend controls, https://doi.org/10.3390/jmse12030472", "Structural-stratigraphic traps, sand-bed controls, partial hydrate fill, and water contacts.", "Explain why geology and clean reservoir context must accompany logs and ML.", "Regional/source interpretation only, not ML labels."),
            ("Aung et al. 2026, Alaska North Slope LWD data acquisition, https://doi.org/10.1021/acs.energyfuels.5c06115", "Direct ANS LWD suite, QC, GR/resistivity/density/neutron/sonic/NMR context, and completion-selection logic.", "Use for direct ANS log-family and QC support.", "Do not use source quick-look intervals as project results."),
            ("Yoneda et al. 2026, ANS HYDRATE 02 NMR T2/permeability, https://doi.org/10.1021/acs.energyfuels.5c05321", "NMR T2, pressure-core/lab permeability, reservoir/seal behavior, and permeability calibration.", "Support NMR/core calibration and producibility-context discussion.", "Permeability is context/calibration, not an occurrence label."),
            ("Singh, Seol, and Myshakin 2021, https://www.osti.gov/servlets/purl/1893637; Chong et al. 2024 / USGS, https://pubs.usgs.gov/publication/70250169", "Leakage-safe well-log ML, selected feature families, occurrence classification, and saturation regression architecture.", "Support separate occurrence and saturation model heads, baselines first, and ANN/Keras as later candidate.", "Method anchor only; no project model metrics yet."),
        ],
    )
    return True


def main() -> None:
    if not DOCX_PATH.exists():
        raise FileNotFoundError(DOCX_PATH)
    document = Document(DOCX_PATH)
    changed = append_science_support_notes(document)
    if changed:
        document.save(DOCX_PATH)
        print(f"Updated {DOCX_PATH}")
    else:
        print(f"Already contained source notes: {DOCX_PATH}")


if __name__ == "__main__":
    main()
